# Generated by Django 5.2.14 on 2026-05-08 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_task_parent_alter_task_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='state',
        ),
        migrations.AddField(
            model_name='worker',
            name='role',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tracker.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DONE', 'Done'), ('WAITING', 'Waiting')], default='WAITING', max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
